#!/usr/bin/env bash
# Generates OpenCvSharpExtern.symbols.props from a list of P/Invoke entry points.
# The list comes from .scratch/symcheck/pinvokes.cs run against the upstream OpenCvSharp.dll.
# Usage: generate-symbols-props.bash <entry-points.txt> <output.props>
set -euo pipefail
if [[ $# -ne 2 ]]; then
    echo "usage: $0 <entry-points.txt> <output.props>" >&2
    exit 1
fi
{
    echo '<?xml version="1.0" encoding="utf-8"?>'
    echo '<!-- Generated by generate-symbols-props.bash. Do not edit by hand. -->'
    echo '<Project>'
    echo '  <ItemGroup>'
    # Sorted and de-duplicated so regenerating produces a stable diff.
    sort -u "$1" | while IFS= read -r symbol; do
        [[ -z "$symbol" ]] && continue
        echo "    <ReferenceNativeSymbol Include=\"$symbol\"><SymbolType>Function</SymbolType></ReferenceNativeSymbol>"
    done
    echo '  </ItemGroup>'
    echo '</Project>'
} > "$2"
